name = "Wold's Vaults"
author = "iwolfking"
version = "0.26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d221867a7739655f4fd6d0193f8cba072e936b8f23493e574d904ac3b8ab965"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
