name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f75a94cbbd8fa629f8230696ec561623b04cf38b1f328987e37097c7e46c6dd"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
