name = "Wold's Vaults"
author = "iwolfking"
version = "0.23.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6e613901a5287afcb7daa5500c55467d0afaf30ca966791d82b39f74b6e4db8"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
