name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b6110435a8cb71a724b273c3a110aaa4984f0079b0bb53cf456666b819eb208"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
