name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e3f9d9891250dbcdbefb0ccf13a9f94606be7be070e556cbcd1f376f66c0747"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
