name = "Wold's Vaults"
author = "iwolfking"
version = "0.23.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04740e6fd23a63a9e8a6b5be7fe24514e6495216d21a174fb211b2da6ecdc1c1"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
