name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5387018098038babf653e4969ab32a8da50ba4b181ab476923c2f8bb87e7e409"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
