name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d655f29cd8eedfc82a2a36b3f5d8727a3ed4ad75d561b93d21c649b633e0c66a"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
