name = "Wold's Vaults"
author = "iwolfking"
version = "0.20.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "907a059569e8b82cb71a718db23f7f02375570338e5e8e9bf57ed2c8b89b0015"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
