name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1313448c20dc7bdfb70dd7adc85908782e5b42130e728b95692bb2e3e8dcda6"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
