name = "Wold's Vaults"
author = "iwolfking"
version = "0.23.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d249aa8ecaec75b350a84344f99184308fd7bc67926c83abb5d63bfc982a801"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
