name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "501a1a47da7d71891dde265565984fcbce31110757e532b05b075a9c6164e387"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
