name = "Wold's Vaults"
author = "iwolfking"
version = "0.26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "903ae1f62f0a3199de097b54dc6ecc0463afc30dcc4e93f83e2d1a174c4685e1"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
