name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4615faae5cbb9ebe9cfcaae8a9b71bd4b5ff04288e8618a313b2072593a6018e"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
