name = "Wold's Vaults"
author = "iwolfking"
version = "0.23.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "950da287452254b5fc287a52e81d9fdc98ed79fb2f07db3af6d36e1bdb35223a"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
