name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1230831ff9f0bbc235c1f5655c92d163f1eec3fc8629425593f4522de69d4015"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
