name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc1037ce0f891febf1e49789f2a6feb0151b14d271ec23d90e3bd201549e5b20"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
