name = "Wold's Vaults"
author = "iwolfking"
version = "0.26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b794c0109286e24d3bf16ddfcd44fd4d8b532ab85e8e37cb2a92b4123f6bc208"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
