name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1499342d7b181b161a6c93bf0cc4b9249d0b9b626a0bc06392d5f328c056332"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
