name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c50246bb38636a7832cd978e1e9619eca4f867ab1f44eeb9ab50b71f8db38ac"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
