name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a07a12daf7e442e7e9ac2ab62709a2fcce0b831ca91630ac3446f3484010fec"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
