name = "Wold's Vaults"
author = "iwolfking"
version = "0.23.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f06d17e6ffdc51e0e564b4f040091dc5bbd1706833555db2ef15b1cb30d65b80"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
