name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff1d077b3a1c68b1056572d33f7ea3dbbe9afaa4bbd9ad0c133e48034278922"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
