name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47b3138a07dac57b6b40653d6b25091482a911d50b70b3002a816a9b21f4b4fe"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
