name = "Wold's Vaults"
author = "iwolfking"
version = "0.23.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73277b38ea15ce182e8f6f9281b0629583921f263f9c4231c55566cd6bc2a3c5"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
