name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42e3be361963ab86b4c8aeb2bb8afe5d067c98663e5ab342748d88961356e3b8"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
