name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d55eaf81b59bf7135b09c1cf78e4021d93aab0d9b2d2b9f0bdbe8b920bd97961"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
