name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f9c213de8bb0cf5a40759c14886d0867b10d6da235a5cb6b9e6a30e64e735ac"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
