name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "504cd52a7f8dd9e7b02745135dc1cfadc597ae74346a4930835760052527cc64"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
