name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d376f24c882f52feabb1ac9a68e43c8ce5fa8cdb098f5d9451f093ebe8fe111"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
