name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e5669672c5ba1f318dea1636605ecf12cd41bbe5ccd018ca032eb7ed4478fc3"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
