name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8abdd03732e5decceb054538378a85b9a31af0b993d123b9b078c8747d46e98"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
