name = "Wold's Vaults"
author = "iwolfking"
version = "0.24.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52845c653317c35652e1957c592749b2e3797fb9e152ad9b8ca8caaaa97b2343"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
