name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d955a56c84797c795aeb4535851a19da59319c895fe508d2afb8141db09e7cb8"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
