name = "Wold's Vaults"
author = "iwolfking"
version = "0.26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9d31844b049250fc0b74d5810072882d4cdd1e1b7c569b496c4e89ea436490"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
