name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d78e3719ab11f817f8f0a102748fa35a1e7f9445638f2e73f72604b67d30c9c6"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
