name = "Wold's Vaults"
author = "iwolfking"
version = "0.25.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6774e59cfcc41ecf854ac8f4974a22246b603c258393cceca3ac18d975b3b40b"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
